apiVersion: v1
kind: ServiceAccount
metadata:
  name: event-toolkit-sa
  namespace: argo-events
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: argo-event-cr
rules:
- apiGroups:
  - argoproj.io/v1alpha1
  resources:
  - workflows
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-event-rb
  namespace: argo-events 
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argo-event-cr
subjects:
- kind: ServiceAccount
  name: event-toolkit-sa
  namespace: argo-events 