apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: webhook
  namespace: argo-events
spec:
  template:
    serviceAccountName: argo-events-sa
  dependencies:
  - name: payload
    eventSourceName: webhook
    eventName: tf-toolkit
  triggers:
  - template:
      name: payload
      k8s:
          group: argoproj.io
          version: v1alpha1
          resource: workflows
          operation: create
          parameters:
            - src:
                dependencyName: payload
                dataKey: body.message
              dest: spec.templates.0.dag.tasks.0.arguments.parameters.0.value
          source:
            resource: #============== Terrafrom Workflow template
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: test-tf-
                namespace: workflows
                labels:
                  workflows.argoproj.io/archive-strategy: "false"
              spec:
                entrypoint: full
                serviceAccountName: workflows
                templates:
                - name: full
                  dag:
                    tasks:
                    - name: task-echo
                      templateRef:                  # You can reference a "template" from another "WorkflowTemplate or ClusterWorkflowTemplate" using this field
                        name: echo-test-template   # This is the name of the "WorkflowTemplate or ClusterWorkflowTemplate" CRD that contains the "template" you want
                        template: echo-test-template # This is the name of the "template" you want to reference
                        clusterScope: true 
                      arguments:
                        parameters:
                        - name: message
                          value: Hello World
                    - name: tf-version-client1
                      templateRef:                  # You can reference a "template" from another "WorkflowTemplate or ClusterWorkflowTemplate" using this field
                        name: tf-version-template   # This is the name of the "WorkflowTemplate or ClusterWorkflowTemplate" CRD that contains the "template" you want
                        template: tf-version-template # This is the name of the "template" you want to reference
                        clusterScope: true 
                    - name: tf-plan-client1
                      arguments:
                        parameters:
                        - name: nsname 
                          value: client1-ns 
                      templateRef:                  # You can reference a "template" from another "WorkflowTemplate or ClusterWorkflowTemplate" using this field
                        name: tf-plan-template   # This is the name of the "WorkflowTemplate or ClusterWorkflowTemplate" CRD that contains the "template" you want
                        template: tf-plan-template # This is the name of the "template" you want to reference
                        clusterScope: true 
                      dependencies:
                      - tf-version-client1
                    - name: tf-apply-client1
                      arguments:
                        parameters:
                        - name: nsname 
                          value: client1-ns 
                      templateRef:                  # You can reference a "template" from another "WorkflowTemplate or ClusterWorkflowTemplate" using this field
                        name: tf-apply-template   # This is the name of the "WorkflowTemplate or ClusterWorkflowTemplate" CRD that contains the "template" you want
                        template: tf-apply-template # This is the name of the "template" you want to reference
                        clusterScope: true 
                      dependencies:
                      - tf-plan-client1
                    - name: tf-version-client2
                      templateRef:                  # You can reference a "template" from another "WorkflowTemplate or ClusterWorkflowTemplate" using this field
                        name: tf-version-template   # This is the name of the "WorkflowTemplate or ClusterWorkflowTemplate" CRD that contains the "template" you want
                        template: tf-version-template # This is the name of the "template" you want to reference
                        clusterScope: true 
                    - name: tf-plan-client2
                      arguments:
                        parameters:
                        - name: nsname 
                          value: client2-ns 
                      templateRef:                  # You can reference a "template" from another "WorkflowTemplate or ClusterWorkflowTemplate" using this field
                        name: tf-plan-template   # This is the name of the "WorkflowTemplate or ClusterWorkflowTemplate" CRD that contains the "template" you want
                        template: tf-plan-template # This is the name of the "template" you want to reference
                        clusterScope: true 
                      dependencies:
                      - tf-version-client2
                    - name: tf-apply-client2
                      arguments:
                        parameters:
                        - name: nsname  
                          value: client2-ns
                      templateRef:                  # You can reference a "template" from another "WorkflowTemplate or ClusterWorkflowTemplate" using this field
                        name: tf-apply-template   # This is the name of the "WorkflowTemplate or ClusterWorkflowTemplate" CRD that contains the "template" you want
                        template: tf-apply-template # This is the name of the "template" you want to reference
                        clusterScope: true 
                      dependencies:
                      - tf-plan-client2
